export let data = [
  {
  request: {
    str: null,
    timestamp: 1588279908,
    loc: {
      city: 'Brooklyn',
      area_code: 718,
      postal_code: '11211',
      lat: 40.7099,
      region_name: 'New York',
      country_code: 'US',
      name: 'Brooklyn, New York US',
      lng: -73.9591
    },
    mode: 'sites',
    dist: 50,
    api: 1
  },
  sites: [
    {
      currents: null,
      distance: '10.37',
      hazards: null,
      lat: '40.5681',
      name: 'Secret Beach',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '16502',
      equipment: null,
      lng: '-73.8946'
    },
    {
      currents: null,
      distance: '12.05',
      hazards: null,
      lat: '40.5455',
      name: 'Black Warrior',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '23554',
      equipment: null,
      lng: '-73.8825'
    },
    {
      currents: null,
      distance: '13.85',
      hazards: null,
      lat: '40.5947',
      name: 'Beach 8th Street',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '23154',
      equipment: null,
      lng: '-73.7428'
    },
    {
      currents: null,
      distance: '14.19',
      hazards: null,
      lat: '40.5935',
      name: 'Atlantic Beach Bridge',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '16881',
      equipment: null,
      lng: '-73.7362'
    },
    {
      currents: null,
      distance: '17.21',
      hazards: null,
      lat: '40.4634',
      name: 'SANDY HOOK SHORE "The Auditorium"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22429',
      equipment: null,
      lng: '-74.0059'
    },
    {
      currents: null,
      distance: '17.71',
      hazards: null,
      lat: '40.4560',
      name: 'SANDY HOOK SHORE "Guardian Park"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22428',
      equipment: null,
      lng: '-74.0048'
    },
    {
      currents: null,
      distance: '18.21',
      hazards: null,
      lat: '40.4481',
      name: 'SANDY HOOK SHORE "Horseshoe Cove"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22430',
      equipment: null,
      lng: '-73.9987'
    },
    {
      currents: null,
      distance: '18.77',
      hazards: null,
      lat: '40.4596',
      name: 'SANDY HOOK "The Pilot Boat"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22424',
      equipment: null,
      lng: '-73.8203'
    },
    {
      currents: null,
      distance: '18.83',
      hazards: null,
      lat: '40.5355',
      name: 'Iberia',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '23552',
      equipment: null,
      lng: '-73.6832'
    },
    {
      currents: null,
      distance: '19.36',
      hazards: null,
      lat: '40.4529',
      name: 'RELIEF "The Lightship"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22423',
      equipment: null,
      lng: '-73.8124'
    },
    {
      currents: null,
      distance: '23.09',
      hazards: null,
      lat: '40.4172',
      name: 'MOHAWK "The RC"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22420',
      equipment: null,
      lng: '-73.7468'
    },
    {
      currents: null,
      distance: '23.20',
      hazards: null,
      lat: '40.4712',
      name: 'LIZZIE D. "The Rum Runner"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22417',
      equipment: null,
      lng: '-73.6481'
    },
    {
      currents: null,
      distance: '24.45',
      hazards: null,
      lat: '40.3569',
      name: 'MACEDONIA',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22418',
      equipment: null,
      lng: '-73.9282'
    },
    {
      currents: null,
      distance: '25.81',
      hazards: null,
      lat: '40.3552',
      name: 'CONTINENT',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22415',
      equipment: null,
      lng: '-73.8050'
    },
    {
      currents: null,
      distance: '27.53',
      hazards: null,
      lat: '40.3117',
      name: 'CHAUNCEY JEROME JR.',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22431',
      equipment: null,
      lng: '-73.9750'
    },
    {
      currents: null,
      distance: '29.29',
      hazards: null,
      lat: '40.2863',
      name: 'LONG BRANCH "The Dual Wrecks"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22432',
      equipment: null,
      lng: '-73.9803'
    },
    {
      currents: null,
      distance: '32.21',
      hazards: null,
      lat: '40.9515',
      name: 'Gwendoline Steers Wreck',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '16374',
      equipment: null,
      lng: '-73.4322'
    },
    {
      currents: null,
      distance: '33.03',
      hazards: null,
      lat: '40.2545',
      name: 'IOANNIS P. GOULANDRIS',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22390',
      equipment: null,
      lng: '-73.7679'
    },
    {
      currents: null,
      distance: '33.03',
      hazards: null,
      lat: '40.2322',
      name: 'New Era Wreck',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '17281',
      equipment: null,
      lng: '-73.9852'
    },
    {
      currents: null,
      distance: '33.17',
      hazards: null,
      lat: '40.2373',
      name: 'PINTA',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22422',
      equipment: null,
      lng: '-73.8480'
    },
    {
      currents: null,
      distance: '35.58',
      hazards: null,
      lat: '40.6392',
      name: 'Oak Beach Park',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '23250',
      equipment: null,
      lng: '-73.2866'
    },
    {
      currents: null,
      distance: '36.20',
      hazards: null,
      lat: '40.2140',
      name: 'CHOAPA',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22391',
      equipment: null,
      lng: '-73.7368'
    },
    {
      currents: null,
      distance: '36.21',
      hazards: null,
      lat: '40.1873',
      name: 'Shark River Inlet',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22167',
      equipment: null,
      lng: '-74.0105'
    },
    {
      currents: null,
      distance: '36.85',
      hazards: null,
      lat: '40.1796',
      name: 'L Street Beach, Shark River',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '23325',
      equipment: null,
      lng: '-74.0337'
    },
    {
      currents: null,
      distance: '36.89',
      hazards: null,
      lat: '40.1775',
      name: 'Malta Wreck',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '18029',
      equipment: null,
      lng: '-74.0111'
    },
    {
      currents: null,
      distance: '36.90',
      hazards: null,
      lat: '40.2860',
      name: 'FORT VICTORIA',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22325',
      equipment: null,
      lng: '-73.5320'
    },
    {
      currents: null,
      distance: '38.19',
      hazards: null,
      lat: '40.1590',
      name: 'SPRING LAKE SHORE "The Ayrshire"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22395',
      equipment: null,
      lng: '-74.0172'
    },
    {
      currents: null,
      distance: '38.69',
      hazards: null,
      lat: '40.1519',
      name: 'SPRING LAKE SHORE "The Spring Lake Wreck"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22433',
      equipment: null,
      lng: '-74.0205'
    },
    {
      currents: null,
      distance: '38.79',
      hazards: null,
      lat: '40.9206',
      name: 'LAKE HOPATCONG',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22438',
      equipment: null,
      lng: '-74.6465'
    },
    {
      currents: null,
      distance: '39.13',
      hazards: null,
      lat: '40.2570',
      name: 'HMS PENTLAND FIRTH',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22342',
      equipment: null,
      lng: '-73.5120'
    },
    {
      currents: null,
      distance: '41.98',
      hazards: null,
      lat: '40.1028',
      name: 'G.A. Venturo',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '23820',
      equipment: null,
      lng: '-73.9888'
    },
    {
      currents: null,
      distance: '42.16',
      hazards: null,
      lat: '40.1024',
      name: 'Manasquan Inlet',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '24561',
      equipment: null,
      lng: '-74.0342'
    },
    {
      currents: null,
      distance: '42.36',
      hazards: null,
      lat: '40.1006',
      name: 'Point Pleasant rail road bridge',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22185',
      equipment: null,
      lng: '-74.0485'
    },
    {
      currents: null,
      distance: '42.52',
      hazards: null,
      lat: '40.0954',
      name: '120 Wreck',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '23472',
      equipment: null,
      lng: '-73.9174'
    },
    {
      currents: null,
      distance: '43.56',
      hazards: null,
      lat: '40.0822',
      name: 'Lizzie H Brayton Wreck',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '18311',
      equipment: null,
      lng: '-74.0365'
    },
    {
      currents: null,
      distance: '43.80',
      hazards: null,
      lat: '40.0761',
      name: 'BRUNETTE "The Doorknob Wreck"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22414',
      equipment: null,
      lng: '-73.9694'
    },
    {
      currents: null,
      distance: '43.80',
      hazards: null,
      lat: '40.0761',
      name: 'DAGHESTAN',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22416',
      equipment: null,
      lng: '-73.9694'
    },
    {
      currents: null,
      distance: '43.90',
      hazards: null,
      lat: '40.1099',
      name: 'ALGOL',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22640',
      equipment: null,
      lng: '-73.6850'
    },
    {
      currents: null,
      distance: '44.67',
      hazards: null,
      lat: '40.0650',
      name: 'Merchant Man',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22397',
      equipment: null,
      lng: '-74.0180'
    },
    {
      currents: null,
      distance: '44.71',
      hazards: null,
      lat: '40.0644',
      name: 'AMITY',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22419',
      equipment: null,
      lng: '-74.0185'
    },
    {
      currents: null,
      distance: '44.73',
      hazards: null,
      lat: '40.0656',
      name: 'Bluffs wreck aka Creole',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '23329',
      equipment: null,
      lng: '-74.0416'
    },
    {
      currents: null,
      distance: '44.94',
      hazards: null,
      lat: '40.0603',
      name: 'DELAWARE',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22327',
      equipment: null,
      lng: '-74.0021'
    },
    {
      currents: null,
      distance: '45.28',
      hazards: null,
      lat: '40.4332',
      name: 'Kennosha (Fire Island Light Ship)',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '23555',
      equipment: null,
      lng: '-73.1770'
    },
    {
      currents: null,
      distance: '45.75',
      hazards: null,
      lat: '40.3664',
      name: 'USS San Diego',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '23551',
      equipment: null,
      lng: '-73.2142'
    },
    {
      currents: null,
      distance: '46.85',
      hazards: null,
      lat: '40.0353',
      name: 'MANTOLOKING SHORE "The Mantoloking Wreck"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22398',
      equipment: null,
      lng: '-74.0490'
    },
    {
      currents: null,
      distance: '46.97',
      hazards: null,
      lat: '40.0336',
      name: 'John Minturn Wreck',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '18325',
      equipment: null,
      lng: '-74.0492'
    },
    {
      currents: null,
      distance: '47.06',
      hazards: null,
      lat: '40.2750',
      name: 'BARDNESS',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22326',
      equipment: null,
      lng: '-73.2700'
    },
    {
      currents: null,
      distance: '47.07',
      hazards: null,
      lat: '40.0322',
      name: 'MANTOLOKING SHORE "The China Wreck"',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22434',
      equipment: null,
      lng: '-74.0498'
    },
    {
      currents: null,
      distance: '47.08',
      hazards: null,
      lat: '40.6186',
      name: 'ROUND VALLEY RESERVOIR',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22435',
      equipment: null,
      lng: '-74.8492'
    },
    {
      currents: null,
      distance: '47.65',
      hazards: null,
      lat: '40.0232',
      name: 'MOHAWK',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '22638',
      equipment: null,
      lng: '-73.8755'
    },
    {
      currents: null,
      distance: '49.51',
      hazards: null,
      lat: '40.5404',
      name: 'USS San Diego Wreck',
      water: null,
      marinelife: null,
      description: null,
      maxdepth: null,
      mindepth: null,
      predive: null,
      id: '16538',
      equipment: null,
      lng: '-73.0418'
    }
  ],
  version: 1,
  loc: {
    city: 'Brooklyn',
    area_code: 718,
    postal_code: '11211',
    lat: 40.7099,
    region_name: 'New York',
    country_code: 'US',
    name: 'Brooklyn, New York US',
    lng: -73.9591
  },
  result: true
}
];
